name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git push --delete origin ${{ github.event.pull_request.head.ref }}
